name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install libraries
      run: sudo apt install -y libserialport0 libserialport-dev git
    - name: Checkout submodules
      run: git submodule init && git submodule update
    - name: make
      run: make
    - name: file
      run: file ./pikon
